### ISSUE TITLE
Doesn't work with 3.4.0.beta3-dev

### ISSUE THREAD

**Issue by bartlomiejwolk** [nolosb/discourse-tag-styles#1]
I installed it from GitHub, added to my active "Default" theme, assigned tags to colors. When inside a category, topics with these tags attached appear as usual, in default gray.

**Comment by nolosb** [comment]
Seems to work for me:

![image](https://github.com/user-attachments/assets/c3e7e45f-9f37-4ac9-8bfb-e9184c9143ee)

You need to set tag styles set to box in system settings:

![image](https://github.com/user-attachments/assets/8f60a80e-0e46-4c44-bd1d-c42cddd4f379)

**Comment by bartlomiejwolk** [comment]
I didn't know about the tag style. Thank you :)
